descriptionFormat: '{product.title} - {title}'
enableVersioning: false
handle: products
hasDimensions: false
hasProductTitleField: true
hasVariantTitleField: false
maxVariants: null
name: Products
productFieldLayouts:
  be72b007-b301-4d30-82d7-53a0ed9a22ec:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\commerce\fieldlayoutelements\ProductTitleField
            uid: e72f9176-462e-488e-a563-2bbfab3987fe
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: eb6c8b6c-8a32-42a9-9ab0-97414e63933d # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c2b63f9e-e23e-47b6-8ac2-10e82f1ca371
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 57dcd468-699f-4123-94e0-7ef4f7c608fa # Colour
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9993725b-6c75-43ae-aaaf-cf374499f2f4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 538464ce-c5c0-49ae-badb-fa161b18063c # Brand
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 22de9eb7-2bce-4648-bcba-8a9a3e40b061
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0b2826e6-4b3f-47c6-a726-df613dcdd607 # Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 49cdbf38-5e25-487e-8ce7-ea68f4246d80
            userCondition: null
            warning: null
            width: 100
          -
            attribute: variants
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\VariantsField
            uid: cac72456-60b5-4587-849e-c2ee4c0943e7
            userCondition: null
            warning: null
        name: Content
        uid: a7cd4d02-6bd5-412d-a716-8006b28c5a61
        userCondition: null
productTitleFormat: ''
siteSettings:
  bd3a4e55-c4e4-473f-8a85-dd23d31febdf: # Sprig Training
    hasUrls: true
    template: ''
    uriFormat: 'products/{slug}'
skuFormat: ''
variantFieldLayouts:
  75e4f84e-390a-46aa-b1d5-3fd21ba50086:
    tabs:
      -
        elementCondition: null
        elements:
          -
            attribute: sku
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: SKU
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: true
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableSkuField
            uid: d14286cf-7500-4425-b8ef-7c6337a87f5d
            userCondition: null
            warning: null
            width: 100
          -
            attribute: price
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: __blank__
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: true
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasablePriceField
            uid: 8cc97127-8745-46fe-819d-69c1c714fa05
            userCondition: null
            warning: null
            width: 100
          -
            attribute: stock
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: Inventory
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: true
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableStockField
            uid: 5fdf5628-f4bd-4391-a664-d76a878606af
            userCondition: null
            warning: null
            width: 100
          -
            attribute: availableForPurchase
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: 'Available for purchase'
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: true
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableAvailableForPurchaseField
            uid: 2f4626e8-f395-42e6-a06f-0e6a2a4dce60
            userCondition: null
            warning: null
            width: 100
          -
            attribute: allowedQty
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: 'Allowed Qty'
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableAllowedQtyField
            uid: 0665c2f7-18ce-4234-942d-8884701f9706
            userCondition: null
            warning: null
            width: 100
          -
            attribute: freeShipping
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: 'Free Shipping'
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: true
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableFreeShippingField
            uid: 98632d73-8ecb-4989-8cc5-7639bc52e933
            userCondition: null
            warning: null
            width: 100
          -
            attribute: promotable
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: Promotable
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: true
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasablePromotableField
            uid: 6b619e57-50d0-42e6-b72f-dffe7c9bd78b
            userCondition: null
            warning: null
            width: 100
          -
            attribute: dimensions
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: Dimensions
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableDimensionsField
            uid: 361617f4-467e-4ad6-aa76-377487e0fe48
            userCondition: null
            warning: null
            width: 100
          -
            attribute: weight
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: Weight
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableWeightField
            uid: c634bcb0-2396-4fb8-91b2-035173c74e46
            userCondition: null
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\commerce\fieldlayoutelements\VariantTitleField
            uid: 86ffda5f-7f11-4604-bf87-2bbf7ddcb04f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 57dcd468-699f-4123-94e0-7ef4f7c608fa # Colour
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6976c542-7895-445e-a7cc-984f83edc4db
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 828f2570-6e7c-4ce8-b040-9b89c681cdde
        userCondition: null
variantTitleFormat: '{product.title}'
