columnSuffix: hpitsupp
handle: colour
instructions: null
name: Colour
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - Yellow
        -
          - value
          - yellow
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - White
        -
          - value
          - white
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Black
        -
          - value
          - black
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
