dateModified: 1715544223
elementSources:
  craft\commerce\elements\Product:
    -
      key: '*'
      type: native
    -
      heading: 'Product Types'
      type: heading
    -
      defaultSort:
        - title
        - asc
      disabled: false
      key: 'productType:76ceebcf-6e96-4ed0-8792-e33851d9b8f1' # Products
      tableAttributes:
        - defaultSku
        - defaultPrice
        - availableForPurchase
        - stock
        - link
      type: native
email:
  fromEmail: ben@putyourlightson.com
  fromName: 'Sprig Training'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  images:
    hasUrls: true
    name: Images
    settings:
      path: '@webroot/assets/images'
    type: craft\fs\Local
    url: /assets/images
meta:
  __names__:
    0b2826e6-4b3f-47c6-a726-df613dcdd607: Description # Description
    57dcd468-699f-4123-94e0-7ef4f7c608fa: Colour # Colour
    76ceebcf-6e96-4ed0-8792-e33851d9b8f1: Products # Products
    78d705b6-3fee-471b-9451-847caf510cde: Dummy # Dummy
    326db6f6-0577-4166-a7f3-c64d1c0b1bc3: Common # Common
    63787053-c58d-42f3-af9c-632e7dc01f35: Images # Images
    a5992712-f8e7-40f9-a127-2b87b50eb960: New # New
    b9be22a6-6ef5-4a3a-9c8f-163610685d49: Articles # Articles
    b1797aea-7808-418c-a68b-1cb07b2b1c7c: Default # Default
    bd3a4e55-c4e4-473f-8a85-dd23d31febdf: 'Sprig Training' # Sprig Training
    d495a9f4-ec12-4552-b53e-346065fabeaa: 'Sprig Training' # Sprig Training
    eb6c8b6c-8a32-42a9-9ab0-97414e63933d: Image # Image
plugins:
  commerce:
    edition: pro
    enabled: true
    licenseKey: W6R0XCZJ5VIQJ99V8UTTA2LQ
    schemaVersion: 4.5.2
  sprig:
    edition: standard
    enabled: true
    schemaVersion: 1.0.1
system:
  edition: pro
  live: true
  name: 'Sprig Training'
  schemaVersion: 4.5.3.0
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
